<?php

namespace Database\Factories;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends Factory<Product>
 */
class ProductFactory extends Factory
{
    protected $model = Product::class;

    public function definition(): array
    {
        $products = self::products();

        $product = fake()->randomElement($products);

        return [
            'name' => $product['name'],
            'slug' => $product['slug'],
            'description' => $product['description'],
            'sku' => $product['sku'],
            'price' => $product['price'],
            'sale_price' => $product['sale_price'] ?? null,
            'quantity' => $product['quantity'] ?? fake()->numberBetween(5, 50),
            'status' => true,
            'featured' => $product['featured'] ?? false,
            'sort_order' => $product['sort_order'] ?? 0,

            'category_id' => Category::where(
                'slug',
                $product['category']
            )->value('id'),

            'brand_id' => Brand::where(
                'slug',
                $product['brand']
            )->value('id'),
        ];
    }

    public static function products(): array
    {
        return [

            // =========================
            // MOBILE PHONES
            // =========================

            [
                'name' => 'Samsung Galaxy S25',
                'slug' => 'samsung-galaxy-s25',
                'sku' => 'SAM-S25-128',
                'brand' => 'samsung',
                'category' => 'android-phones',
                'description' => 'Samsung Galaxy S25 with a powerful processor, advanced camera system and vibrant AMOLED display.',
                'price' => 39999,
                'sale_price' => 37999,
                'quantity' => 25,
                'featured' => true,
            ],

            [
                'name' => 'Samsung Galaxy A56 5G',
                'slug' => 'samsung-galaxy-a56-5g',
                'sku' => 'SAM-A56-256',
                'brand' => 'samsung',
                'category' => 'mid-range-phones',
                'description' => 'Samsung Galaxy A56 5G featuring a high quality AMOLED display, capable cameras and long battery life.',
                'price' => 23999,
                'sale_price' => 22499,
                'quantity' => 40,
                'featured' => true,
            ],

            [
                'name' => 'Apple iPhone 16 Pro',
                'slug' => 'apple-iphone-16-pro',
                'sku' => 'APP-IP16P-128',
                'brand' => 'apple',
                'category' => 'iphones',
                'description' => 'iPhone 16 Pro with a titanium design, Pro camera system and powerful Apple silicon.',
                'price' => 59999,
                'sale_price' => 57499,
                'quantity' => 15,
                'featured' => true,
            ],

            [
                'name' => 'Apple iPhone 16',
                'slug' => 'apple-iphone-16',
                'sku' => 'APP-IP16-128',
                'brand' => 'apple',
                'category' => 'iphones',
                'description' => 'iPhone 16 with a modern design, advanced camera system and excellent performance.',
                'price' => 46999,
                'sale_price' => null,
                'quantity' => 20,
                'featured' => true,
            ],

            [
                'name' => 'Xiaomi Redmi Note 14 Pro',
                'slug' => 'xiaomi-redmi-note-14-pro',
                'sku' => 'XIA-RN14P-256',
                'brand' => 'xiaomi',
                'category' => 'mid-range-phones',
                'description' => 'Redmi Note 14 Pro with a high resolution display, powerful performance and advanced camera system.',
                'price' => 15999,
                'sale_price' => 14999,
                'quantity' => 35,
            ],

            [
                'name' => 'Xiaomi Redmi Note 14',
                'slug' => 'xiaomi-redmi-note-14',
                'sku' => 'XIA-RN14-128',
                'brand' => 'xiaomi',
                'category' => 'budget-phones',
                'description' => 'Redmi Note 14 offering reliable performance, a large display and long battery life.',
                'price' => 10999,
                'sale_price' => 9999,
                'quantity' => 50,
            ],

            [
                'name' => 'OnePlus 13',
                'slug' => 'oneplus-13',
                'sku' => 'ONE-13-256',
                'brand' => 'oneplus',
                'category' => 'flagship-phones',
                'description' => 'OnePlus 13 flagship smartphone with high performance hardware and a premium display.',
                'price' => 42999,
                'sale_price' => 40999,
                'quantity' => 18,
                'featured' => true,
            ],

            [
                'name' => 'Google Pixel 9 Pro',
                'slug' => 'google-pixel-9-pro',
                'sku' => 'GOO-P9P-256',
                'brand' => 'google',
                'category' => 'flagship-phones',
                'description' => 'Google Pixel 9 Pro with advanced AI features, professional camera capabilities and a premium display.',
                'price' => 49999,
                'sale_price' => null,
                'quantity' => 12,
            ],

            // =========================
            // LAPTOPS
            // =========================

            [
                'name' => 'Lenovo IdeaPad Slim 3',
                'slug' => 'lenovo-ideapad-slim-3',
                'sku' => 'LEN-IPS3-I5',
                'brand' => 'lenovo',
                'category' => 'student-laptops',
                'description' => 'Lenovo IdeaPad Slim 3 designed for students and everyday productivity.',
                'price' => 28999,
                'sale_price' => 27499,
                'quantity' => 20,
            ],

            [
                'name' => 'Dell Latitude 5440',
                'slug' => 'dell-latitude-5440',
                'sku' => 'DEL-L5440-I5',
                'brand' => 'dell',
                'category' => 'business-laptops',
                'description' => 'Dell Latitude 5440 business laptop designed for productivity and professional workloads.',
                'price' => 34999,
                'sale_price' => null,
                'quantity' => 15,
                'featured' => true,
            ],

            [
                'name' => 'HP EliteBook 840 G10',
                'slug' => 'hp-elitebook-840-g10',
                'sku' => 'HP-EB840-G10',
                'brand' => 'hp',
                'category' => 'business-laptops',
                'description' => 'HP EliteBook 840 G10 designed for business users with strong performance and premium build quality.',
                'price' => 42999,
                'sale_price' => 40999,
                'quantity' => 10,
            ],

            [
                'name' => 'ASUS ROG Strix G16',
                'slug' => 'asus-rog-strix-g16',
                'sku' => 'ASU-ROG-G16',
                'brand' => 'asus',
                'category' => 'gaming-laptops',
                'description' => 'ASUS ROG Strix G16 gaming laptop built for demanding games and high performance workloads.',
                'price' => 69999,
                'sale_price' => 67499,
                'quantity' => 8,
                'featured' => true,
            ],

            [
                'name' => 'MSI Katana 15',
                'slug' => 'msi-katana-15',
                'sku' => 'MSI-KAT15',
                'brand' => 'msi',
                'category' => 'gaming-laptops',
                'description' => 'MSI Katana 15 gaming laptop designed for modern games and demanding applications.',
                'price' => 54999,
                'sale_price' => 52999,
                'quantity' => 10,
            ],

            [
                'name' => 'Acer Aspire 5',
                'slug' => 'acer-aspire-5',
                'sku' => 'ACE-AS5-I5',
                'brand' => 'acer',
                'category' => 'student-laptops',
                'description' => 'Acer Aspire 5 laptop suitable for studying, office work and everyday computing.',
                'price' => 26999,
                'sale_price' => 25499,
                'quantity' => 25,
            ],

            [
                'name' => 'Apple MacBook Air M3',
                'slug' => 'apple-macbook-air-m3',
                'sku' => 'APP-MBA-M3',
                'brand' => 'apple',
                'category' => 'professional-laptops',
                'description' => 'MacBook Air powered by Apple M3 chip with a lightweight design and excellent battery life.',
                'price' => 59999,
                'sale_price' => 57999,
                'quantity' => 12,
                'featured' => true,
            ],

            // =========================
            // MONITORS
            // =========================

            [
                'name' => 'Samsung Odyssey G5 27"',
                'slug' => 'samsung-odyssey-g5-27',
                'sku' => 'SAM-ODG5-27',
                'brand' => 'samsung',
                'category' => 'gaming-monitors',
                'description' => 'Samsung Odyssey G5 gaming monitor with a curved display and high refresh rate.',
                'price' => 18999,
                'sale_price' => 17499,
                'quantity' => 14,
                'featured' => true,
            ],

            [
                'name' => 'LG UltraGear 27"',
                'slug' => 'lg-ultragear-27',
                'sku' => 'LG-UG-27',
                'brand' => 'lg',
                'category' => 'gaming-monitors',
                'description' => 'LG UltraGear gaming monitor designed for smooth gameplay and fast response times.',
                'price' => 16999,
                'sale_price' => null,
                'quantity' => 18,
            ],

            // =========================
            // TVs
            // =========================

            [
                'name' => 'Samsung 55 Inch QLED 4K Smart TV',
                'slug' => 'samsung-55-inch-qled-4k-smart-tv',
                'sku' => 'SAM-TV55-QLED',
                'brand' => 'samsung',
                'category' => 'qled-tvs',
                'description' => 'Samsung 55-inch QLED 4K Smart TV with vivid colors and smart entertainment features.',
                'price' => 45999,
                'sale_price' => 42999,
                'quantity' => 7,
                'featured' => true,
            ],

            [
                'name' => 'LG 55 Inch OLED Smart TV',
                'slug' => 'lg-55-inch-oled-smart-tv',
                'sku' => 'LG-TV55-OLED',
                'brand' => 'lg',
                'category' => 'oled-tvs',
                'description' => 'LG 55-inch OLED Smart TV delivering deep blacks, rich colors and premium picture quality.',
                'price' => 54999,
                'sale_price' => 51999,
                'quantity' => 6,
                'featured' => true,
            ],

            [
                'name' => 'TCL 50 Inch 4K Smart TV',
                'slug' => 'tcl-50-inch-4k-smart-tv',
                'sku' => 'TCL-TV50-4K',
                'brand' => 'tcl',
                'category' => '4k-tvs',
                'description' => 'TCL 50-inch 4K Smart TV with smart entertainment features and high resolution picture quality.',
                'price' => 23999,
                'sale_price' => 22499,
                'quantity' => 15,
            ],

            // =========================
            // AUDIO
            // =========================

            [
                'name' => 'JBL Tune 770NC',
                'slug' => 'jbl-tune-770nc',
                'sku' => 'JBL-T770NC',
                'brand' => 'jbl',
                'category' => 'headphones',
                'description' => 'JBL Tune 770NC wireless headphones with active noise cancellation and long battery life.',
                'price' => 6999,
                'sale_price' => 6499,
                'quantity' => 30,
                'featured' => true,
            ],

            [
                'name' => 'JBL Charge 5',
                'slug' => 'jbl-charge-5',
                'sku' => 'JBL-CHG5',
                'brand' => 'jbl',
                'category' => 'bluetooth-speakers',
                'description' => 'JBL Charge 5 portable Bluetooth speaker with powerful sound and long battery life.',
                'price' => 6999,
                'sale_price' => 6499,
                'quantity' => 25,
            ],

            [
                'name' => 'Sony WH-1000XM5',
                'slug' => 'sony-wh-1000xm5',
                'sku' => 'SONY-WH1000XM5',
                'brand' => 'sony',
                'category' => 'headphones',
                'description' => 'Sony WH-1000XM5 premium wireless headphones with advanced noise cancellation.',
                'price' => 18999,
                'sale_price' => 17499,
                'quantity' => 10,
                'featured' => true,
            ],

            // =========================
            // MOBILE ACCESSORIES
            // =========================

            [
                'name' => 'Anker 323 Charger',
                'slug' => 'anker-323-charger',
                'sku' => 'ANK-323-CH',
                'brand' => 'anker',
                'category' => 'chargers',
                'description' => 'Anker 323 fast charger designed for smartphones and other compatible devices.',
                'price' => 999,
                'sale_price' => 899,
                'quantity' => 60,
            ],

            [
                'name' => 'Anker PowerCore 20000',
                'slug' => 'anker-powercore-20000',
                'sku' => 'ANK-PC20K',
                'brand' => 'anker',
                'category' => 'power-banks',
                'description' => 'Anker PowerCore 20000mAh portable power bank for charging mobile devices on the go.',
                'price' => 2499,
                'sale_price' => 2299,
                'quantity' => 40,
            ],

            // =========================
            // STORAGE
            // =========================

            [
                'name' => 'Kingston NV2 1TB NVMe SSD',
                'slug' => 'kingston-nv2-1tb-nvme-ssd',
                'sku' => 'KIN-NV2-1TB',
                'brand' => 'kingston',
                'category' => 'ssds',
                'description' => 'Kingston NV2 1TB NVMe SSD providing fast storage performance for desktops and laptops.',
                'price' => 4999,
                'sale_price' => 4499,
                'quantity' => 35,
                'featured' => true,
            ],

            [
                'name' => 'Samsung 990 EVO 1TB SSD',
                'slug' => 'samsung-990-evo-1tb-ssd',
                'sku' => 'SAM-990EVO-1TB',
                'brand' => 'samsung',
                'category' => 'ssds',
                'description' => 'Samsung 990 EVO 1TB SSD designed for high performance storage and demanding applications.',
                'price' => 6999,
                'sale_price' => 6499,
                'quantity' => 20,
            ],

            [
                'name' => 'Western Digital 1TB External SSD',
                'slug' => 'western-digital-1tb-external-ssd',
                'sku' => 'WD-EXT-SSD-1TB',
                'brand' => 'western-digital',
                'category' => 'external-ssds',
                'description' => 'Western Digital 1TB portable SSD for fast and reliable external storage.',
                'price' => 6999,
                'sale_price' => null,
                'quantity' => 15,
            ],

            // =========================
            // GAMING
            // =========================

            [
                'name' => 'PlayStation 5 Slim',
                'slug' => 'playstation-5-slim',
                'sku' => 'PS5-SLIM',
                'brand' => 'playstation',
                'category' => 'playstation',
                'description' => 'PlayStation 5 Slim gaming console with high performance hardware and fast SSD storage.',
                'price' => 29999,
                'sale_price' => 28999,
                'quantity' => 10,
                'featured' => true,
            ],

            [
                'name' => 'Xbox Series X',
                'slug' => 'xbox-series-x',
                'sku' => 'XBX-SERIES-X',
                'brand' => 'xbox',
                'category' => 'xbox',
                'description' => 'Xbox Series X high performance gaming console designed for next generation gaming.',
                'price' => 31999,
                'sale_price' => null,
                'quantity' => 8,
                'featured' => true,
            ],

            [
                'name' => 'Samsung Galaxy S25 Plus',
                'slug' => 'samsung-galaxy-s25-plus',
                'sku' => 'SAM-S25P-256',
                'brand' => 'samsung',
                'category' => 'flagship-phones',
                'description' => 'Samsung Galaxy S25 Plus with a vivid AMOLED display, flagship performance and an advanced camera system.',
                'price' => 47999,
                'sale_price' => 45999,
                'quantity' => 12,
                'featured' => true,
            ],
            [
                'name' => 'Samsung Galaxy S24 FE',
                'slug' => 'samsung-galaxy-s24-fe',
                'sku' => 'SAM-S24FE-128',
                'brand' => 'samsung',
                'category' => 'mid-range-phones',
                'description' => 'Samsung Galaxy S24 FE with a premium display, capable cameras and strong everyday performance.',
                'price' => 25999,
                'sale_price' => 24499,
                'quantity' => 18,
                'featured' => false,
            ],
            [
                'name' => 'Samsung Galaxy A35 5G',
                'slug' => 'samsung-galaxy-a35-5g',
                'sku' => 'SAM-A35-256',
                'brand' => 'samsung',
                'category' => 'mid-range-phones',
                'description' => 'Samsung Galaxy A35 5G with an AMOLED display, versatile cameras and long battery life.',
                'price' => 16999,
                'sale_price' => 15999,
                'quantity' => 25,
                'featured' => false,
            ],
            [
                'name' => 'Apple iPhone 16 Pro Max',
                'slug' => 'apple-iphone-16-pro-max',
                'sku' => 'APP-IP16PM-256',
                'brand' => 'apple',
                'category' => 'iphones',
                'description' => 'iPhone 16 Pro Max with a titanium design, Pro camera system and powerful Apple silicon.',
                'price' => 69999,
                'sale_price' => 66999,
                'quantity' => 8,
                'featured' => true,
            ],
            [
                'name' => 'Apple iPhone 15 Pro',
                'slug' => 'apple-iphone-15-pro',
                'sku' => 'APP-IP15P-128',
                'brand' => 'apple',
                'category' => 'iphones',
                'description' => 'iPhone 15 Pro with a titanium design, Pro camera system and high-performance Apple silicon.',
                'price' => 54999,
                'sale_price' => 52499,
                'quantity' => 9,
                'featured' => true,
            ],
            [
                'name' => 'Apple iPhone 15',
                'slug' => 'apple-iphone-15',
                'sku' => 'APP-IP15-128',
                'brand' => 'apple',
                'category' => 'iphones',
                'description' => 'iPhone 15 with a Super Retina display, advanced cameras and modern performance.',
                'price' => 41999,
                'sale_price' => 39999,
                'quantity' => 15,
                'featured' => false,
            ],
            [
                'name' => 'Xiaomi Redmi Note 14 Pro',
                'slug' => 'xiaomi-redmi-note-14-pro',
                'sku' => 'XIA-RN14P-256',
                'brand' => 'xiaomi',
                'category' => 'mid-range-phones',
                'description' => 'Redmi Note 14 Pro with a high-resolution display, capable cameras and fast charging.',
                'price' => 17999,
                'sale_price' => 16999,
                'quantity' => 22,
                'featured' => true,
            ],
            [
                'name' => 'Xiaomi Poco X7 Pro',
                'slug' => 'xiaomi-poco-x7-pro',
                'sku' => 'XIA-POCO-X7P-256',
                'brand' => 'xiaomi',
                'category' => 'mid-range-phones',
                'description' => 'POCO X7 Pro built for fast performance, gaming and high-refresh-rate entertainment.',
                'price' => 19999,
                'sale_price' => 18999,
                'quantity' => 18,
                'featured' => true,
            ],
            [
                'name' => 'OnePlus 13R',
                'slug' => 'oneplus-13r',
                'sku' => 'ONE-13R-256',
                'brand' => 'oneplus',
                'category' => 'flagship-phones',
                'description' => 'OnePlus 13R with powerful performance, a high-refresh-rate display and a versatile camera setup.',
                'price' => 29999,
                'sale_price' => 28499,
                'quantity' => 14,
                'featured' => false,
            ],
            [
                'name' => 'Google Pixel 9',
                'slug' => 'google-pixel-9',
                'sku' => 'GOO-P9-128',
                'brand' => 'google',
                'category' => 'flagship-phones',
                'description' => 'Google Pixel 9 with advanced computational photography and clean Android software.',
                'price' => 39999,
                'sale_price' => 37999,
                'quantity' => 10,
                'featured' => true,
            ],
            [
                'name' => 'Lenovo Legion 5',
                'slug' => 'lenovo-legion-5',
                'sku' => 'LEN-LEG5-R7',
                'brand' => 'lenovo',
                'category' => 'gaming-laptops',
                'description' => 'Lenovo Legion 5 gaming laptop designed for demanding games and high-performance workloads.',
                'price' => 54999,
                'sale_price' => 52999,
                'quantity' => 8,
                'featured' => true,
            ],
            [
                'name' => 'Lenovo ThinkPad E14 Gen 6',
                'slug' => 'lenovo-thinkpad-e14-gen-6',
                'sku' => 'LEN-TP-E14G6',
                'brand' => 'lenovo',
                'category' => 'business-laptops',
                'description' => 'Lenovo ThinkPad E14 Gen 6 built for business productivity, portability and dependable daily work.',
                'price' => 37999,
                'sale_price' => 35999,
                'quantity' => 12,
                'featured' => false,
            ],
            [
                'name' => 'Dell XPS 13',
                'slug' => 'dell-xps-13',
                'sku' => 'DEL-XPS13',
                'brand' => 'dell',
                'category' => 'professional-laptops',
                'description' => 'Dell XPS 13 premium laptop with a compact design and strong productivity performance.',
                'price' => 49999,
                'sale_price' => 47999,
                'quantity' => 9,
                'featured' => true,
            ],
            [
                'name' => 'Dell Inspiron 15 3530',
                'slug' => 'dell-inspiron-15-3530',
                'sku' => 'DEL-INS15-3530',
                'brand' => 'dell',
                'category' => 'student-laptops',
                'description' => 'Dell Inspiron 15 designed for study, office work, browsing and everyday computing.',
                'price' => 29999,
                'sale_price' => 28499,
                'quantity' => 18,
                'featured' => false,
            ],
            [
                'name' => 'HP Pavilion 15',
                'slug' => 'hp-pavilion-15',
                'sku' => 'HP-PAV15-I5',
                'brand' => 'hp',
                'category' => 'student-laptops',
                'description' => 'HP Pavilion 15 offering balanced performance for study, work and everyday entertainment.',
                'price' => 28999,
                'sale_price' => 27499,
                'quantity' => 20,
                'featured' => false,
            ],
            [
                'name' => 'HP Victus 15',
                'slug' => 'hp-victus-15',
                'sku' => 'HP-VIC15-G5',
                'brand' => 'hp',
                'category' => 'gaming-laptops',
                'description' => 'HP Victus 15 gaming laptop with dedicated graphics for modern games.',
                'price' => 44999,
                'sale_price' => 42999,
                'quantity' => 10,
                'featured' => true,
            ],
            [
                'name' => 'ASUS ROG Zephyrus G14',
                'slug' => 'asus-rog-zephyrus-g14',
                'sku' => 'ASU-ROG-G14',
                'brand' => 'asus',
                'category' => 'gaming-laptops',
                'description' => 'ASUS ROG Zephyrus G14 compact gaming laptop combining powerful hardware with portability.',
                'price' => 74999,
                'sale_price' => 71999,
                'quantity' => 6,
                'featured' => true,
            ],
            [
                'name' => 'ASUS Vivobook 15',
                'slug' => 'asus-vivobook-15',
                'sku' => 'ASU-VIVO15',
                'brand' => 'asus',
                'category' => 'student-laptops',
                'description' => 'ASUS Vivobook 15 designed for productivity, study and everyday entertainment.',
                'price' => 26999,
                'sale_price' => 25499,
                'quantity' => 20,
                'featured' => false,
            ],
            [
                'name' => 'MSI Raider GE68 HX',
                'slug' => 'msi-raider-ge68-hx',
                'sku' => 'MSI-RGE68HX',
                'brand' => 'msi',
                'category' => 'gaming-laptops',
                'description' => 'MSI Raider GE68 HX high-performance gaming laptop for demanding games and workloads.',
                'price' => 89999,
                'sale_price' => 86999,
                'quantity' => 5,
                'featured' => true,
            ],
            [
                'name' => 'Acer Nitro V 15',
                'slug' => 'acer-nitro-v-15',
                'sku' => 'ACE-NITROV15',
                'brand' => 'acer',
                'category' => 'gaming-laptops',
                'description' => 'Acer Nitro V 15 gaming laptop offering dedicated graphics and strong performance.',
                'price' => 39999,
                'sale_price' => 37999,
                'quantity' => 12,
                'featured' => false,
            ],
            [
                'name' => 'Apple MacBook Air M2',
                'slug' => 'apple-macbook-air-m2',
                'sku' => 'APP-MBA-M2',
                'brand' => 'apple',
                'category' => 'professional-laptops',
                'description' => 'MacBook Air with M2 chip, lightweight design and excellent battery life.',
                'price' => 44999,
                'sale_price' => 42999,
                'quantity' => 14,
                'featured' => true,
            ],
            [
                'name' => 'Apple MacBook Pro 14 M3',
                'slug' => 'apple-macbook-pro-14-m3',
                'sku' => 'APP-MBP14-M3',
                'brand' => 'apple',
                'category' => 'professional-laptops',
                'description' => 'MacBook Pro 14 with M3 performance, a premium display and professional capabilities.',
                'price' => 69999,
                'sale_price' => 66999,
                'quantity' => 7,
                'featured' => true,
            ],
            [
                'name' => 'ASUS ROG Strix G35',
                'slug' => 'asus-rog-strix-g35',
                'sku' => 'ASU-ROG-G35',
                'brand' => 'asus',
                'category' => 'gaming-pcs',
                'description' => 'ASUS ROG Strix G35 gaming desktop designed for demanding gaming and high-performance workloads.',
                'price' => 89999,
                'sale_price' => 86999,
                'quantity' => 5,
                'featured' => true,
            ],
            [
                'name' => 'HP ProDesk 400 G9',
                'slug' => 'hp-prodesk-400-g9',
                'sku' => 'HP-PRODESK-G9',
                'brand' => 'hp',
                'category' => 'office-pcs',
                'description' => 'HP ProDesk 400 G9 compact business desktop for office productivity.',
                'price' => 24999,
                'sale_price' => 23499,
                'quantity' => 15,
                'featured' => false,
            ],
            [
                'name' => 'Dell OptiPlex 7010',
                'slug' => 'dell-optiplex-7010',
                'sku' => 'DEL-OPT7010',
                'brand' => 'dell',
                'category' => 'office-pcs',
                'description' => 'Dell OptiPlex 7010 business desktop designed for reliable office productivity.',
                'price' => 27999,
                'sale_price' => 26499,
                'quantity' => 12,
                'featured' => false,
            ],
            [
                'name' => 'Apple iMac 24 M3',
                'slug' => 'apple-imac-24-m3',
                'sku' => 'APP-IMAC24-M3',
                'brand' => 'apple',
                'category' => 'all-in-one-pcs',
                'description' => '24-inch iMac with Apple silicon, a slim all-in-one design and a high-resolution display.',
                'price' => 59999,
                'sale_price' => 57999,
                'quantity' => 8,
                'featured' => true,
            ],
            [
                'name' => 'Intel Core i7-14700K',
                'slug' => 'intel-core-i7-14700k',
                'sku' => 'INT-I714700K',
                'brand' => 'intel',
                'category' => 'processors',
                'description' => 'Intel Core i7-14700K desktop processor for high-performance gaming and productivity.',
                'price' => 21999,
                'sale_price' => 20999,
                'quantity' => 15,
                'featured' => true,
            ],
            [
                'name' => 'AMD Ryzen 7 7800X3D',
                'slug' => 'amd-ryzen-7-7800x3d',
                'sku' => 'AMD-R7-7800X3D',
                'brand' => 'amd',
                'category' => 'processors',
                'description' => 'AMD Ryzen 7 7800X3D processor optimized for high-performance gaming.',
                'price' => 22999,
                'sale_price' => 21499,
                'quantity' => 12,
                'featured' => true,
            ],
            [
                'name' => 'NVIDIA GeForce RTX 4070 Super',
                'slug' => 'nvidia-geforce-rtx-4070-super',
                'sku' => 'NV-RTX4070S',
                'brand' => 'nvidia',
                'category' => 'graphics-cards',
                'description' => 'NVIDIA GeForce RTX 4070 Super graphics card for high-resolution gaming and creative workloads.',
                'price' => 39999,
                'sale_price' => 37999,
                'quantity' => 8,
                'featured' => true,
            ],
            [
                'name' => 'ASUS Dual RTX 4060',
                'slug' => 'asus-dual-rtx-4060',
                'sku' => 'ASU-RTX4060',
                'brand' => 'asus',
                'category' => 'graphics-cards',
                'description' => 'ASUS Dual GeForce RTX 4060 graphics card for efficient 1080p and 1440p gaming.',
                'price' => 21999,
                'sale_price' => 20499,
                'quantity' => 14,
                'featured' => false,
            ],
            [
                'name' => 'MSI MAG B650 Tomahawk WiFi',
                'slug' => 'msi-mag-b650-tomahawk-wifi',
                'sku' => 'MSI-B650-TOMAHAWK',
                'brand' => 'msi',
                'category' => 'motherboards',
                'description' => 'MSI MAG B650 Tomahawk WiFi motherboard for modern AMD desktop builds.',
                'price' => 11999,
                'sale_price' => 10999,
                'quantity' => 10,
                'featured' => false,
            ],
            [
                'name' => 'Corsair Vengeance 32GB DDR5',
                'slug' => 'corsair-vengeance-32gb-ddr5',
                'sku' => 'COR-VEN32-DDR5',
                'brand' => 'corsair',
                'category' => 'ram',
                'description' => 'Corsair Vengeance 32GB DDR5 memory kit for modern desktop performance.',
                'price' => 4999,
                'sale_price' => 4599,
                'quantity' => 30,
                'featured' => false,
            ],
            [
                'name' => 'Samsung 990 Pro 2TB SSD',
                'slug' => 'samsung-990-pro-2tb-ssd',
                'sku' => 'SAM-990PRO-2TB',
                'brand' => 'samsung',
                'category' => 'ssds',
                'description' => 'Samsung 990 Pro 2TB NVMe SSD for gaming and professional workloads.',
                'price' => 11999,
                'sale_price' => 10999,
                'quantity' => 15,
                'featured' => true,
            ],
            [
                'name' => 'Kingston Fury Beast 32GB DDR5',
                'slug' => 'kingston-fury-beast-32gb-ddr5',
                'sku' => 'KIN-FURY32-DDR5',
                'brand' => 'kingston',
                'category' => 'ram',
                'description' => 'Kingston Fury Beast 32GB DDR5 desktop memory kit for high-performance systems.',
                'price' => 4499,
                'sale_price' => 4199,
                'quantity' => 25,
                'featured' => false,
            ],
            [
                'name' => 'WD Black SN850X 2TB',
                'slug' => 'wd-black-sn850x-2tb',
                'sku' => 'WD-SN850X-2TB',
                'brand' => 'western-digital',
                'category' => 'ssds',
                'description' => 'WD Black SN850X 2TB NVMe SSD built for fast gaming and demanding applications.',
                'price' => 10999,
                'sale_price' => 9999,
                'quantity' => 14,
                'featured' => true,
            ],
            [
                'name' => 'Seagate BarraCuda 2TB',
                'slug' => 'seagate-barracuda-2tb',
                'sku' => 'SEA-BARR-2TB',
                'brand' => 'seagate',
                'category' => 'hard-drives',
                'description' => 'Seagate BarraCuda 2TB hard drive for desktop storage and everyday data needs.',
                'price' => 2999,
                'sale_price' => 2799,
                'quantity' => 25,
                'featured' => false,
            ],
            [
                'name' => 'Corsair RM750e 750W',
                'slug' => 'corsair-rm750e-750w',
                'sku' => 'COR-RM750E',
                'brand' => 'corsair',
                'category' => 'power-supplies',
                'description' => 'Corsair RM750e 750W power supply designed for reliable modern PC builds.',
                'price' => 6999,
                'sale_price' => 6499,
                'quantity' => 12,
                'featured' => false,
            ],
            [
                'name' => 'Samsung Odyssey G7 32',
                'slug' => 'samsung-odyssey-g7-32',
                'sku' => 'SAM-ODG7-32',
                'brand' => 'samsung',
                'category' => 'gaming-monitors',
                'description' => 'Samsung Odyssey G7 32-inch gaming monitor with a high refresh rate and immersive curved display.',
                'price' => 29999,
                'sale_price' => 28499,
                'quantity' => 8,
                'featured' => true,
            ],
            [
                'name' => 'LG UltraGear 32GS95UE',
                'slug' => 'lg-ultragear-32gs95ue',
                'sku' => 'LG-UG32GS95',
                'brand' => 'lg',
                'category' => 'gaming-monitors',
                'description' => 'LG UltraGear 32GS95UE gaming monitor designed for high-performance PC gaming.',
                'price' => 59999,
                'sale_price' => 57499,
                'quantity' => 5,
                'featured' => true,
            ],
            [
                'name' => 'Dell UltraSharp U2723QE',
                'slug' => 'dell-ultrasharp-u2723qe',
                'sku' => 'DEL-U2723QE',
                'brand' => 'dell',
                'category' => 'professional-monitors',
                'description' => 'Dell UltraSharp U2723QE 4K monitor designed for professional productivity.',
                'price' => 29999,
                'sale_price' => 28499,
                'quantity' => 8,
                'featured' => false,
            ],
            [
                'name' => 'Samsung 43 Inch Crystal UHD 4K TV',
                'slug' => 'samsung-43-inch-crystal-uhd-4k-tv',
                'sku' => 'SAM-TV43-4K',
                'brand' => 'samsung',
                'category' => '4k-tvs',
                'description' => 'Samsung 43-inch Crystal UHD 4K Smart TV for clear everyday entertainment and streaming.',
                'price' => 22999,
                'sale_price' => 21499,
                'quantity' => 12,
                'featured' => false,
            ],
            [
                'name' => 'LG 50 Inch QNED 4K Smart TV',
                'slug' => 'lg-50-inch-qned-4k-smart-tv',
                'sku' => 'LG-QNED50-4K',
                'brand' => 'lg',
                'category' => '4k-tvs',
                'description' => 'LG 50-inch QNED 4K Smart TV combining high-resolution picture quality with smart entertainment.',
                'price' => 26999,
                'sale_price' => 25499,
                'quantity' => 9,
                'featured' => false,
            ],
            [
                'name' => 'Sony Bravia 8 OLED 55',
                'slug' => 'sony-bravia-8-oled-55',
                'sku' => 'SONY-BRAVIA8-55',
                'brand' => 'sony',
                'category' => 'oled-tvs',
                'description' => 'Sony Bravia 8 55-inch OLED TV with premium picture quality and smart entertainment features.',
                'price' => 69999,
                'sale_price' => 66999,
                'quantity' => 4,
                'featured' => true,
            ],
            [
                'name' => 'Samsung 520L French Door Refrigerator',
                'slug' => 'samsung-520l-french-door-refrigerator',
                'sku' => 'SAM-FRIDGE-520',
                'brand' => 'samsung',
                'category' => 'refrigerators',
                'description' => 'Samsung French Door refrigerator with large storage capacity and modern cooling features.',
                'price' => 69999,
                'sale_price' => 66999,
                'quantity' => 5,
                'featured' => true,
            ],
            [
                'name' => 'LG 9KG Front Load Washing Machine',
                'slug' => 'lg-9kg-front-load-washing-machine',
                'sku' => 'LG-WM-9KG',
                'brand' => 'lg',
                'category' => 'washing-machines',
                'description' => 'LG 9KG front-load washing machine designed for efficient everyday laundry.',
                'price' => 32999,
                'sale_price' => 30999,
                'quantity' => 7,
                'featured' => false,
            ],
            [
                'name' => 'Beko 10 Place Dishwasher',
                'slug' => 'beko-10-place-dishwasher',
                'sku' => 'BEKO-DW10',
                'brand' => 'beko',
                'category' => 'dishwashers',
                'description' => 'Beko dishwasher designed for efficient cleaning and convenient home use.',
                'price' => 23999,
                'sale_price' => 22499,
                'quantity' => 8,
                'featured' => false,
            ],
            [
                'name' => 'Philips Airfryer XXL',
                'slug' => 'philips-airfryer-xxl',
                'sku' => 'PHI-AF-XXL',
                'brand' => 'philips',
                'category' => 'home-appliances',
                'description' => 'Philips Airfryer XXL designed for convenient cooking with hot-air technology.',
                'price' => 9999,
                'sale_price' => 9299,
                'quantity' => 15,
                'featured' => false,
            ],
            [
                'name' => 'TCL Inverter Split AC 1.5HP',
                'slug' => 'tcl-inverter-split-ac-1-5hp',
                'sku' => 'TCL-AC-1.5HP',
                'brand' => 'tcl',
                'category' => 'inverter-air-conditioners',
                'description' => 'TCL inverter split air conditioner designed for efficient cooling.',
                'price' => 27999,
                'sale_price' => 26499,
                'quantity' => 8,
                'featured' => true,
            ],
            [
                'name' => 'Hisense 2HP Split AC',
                'slug' => 'hisense-2hp-split-ac',
                'sku' => 'HIS-AC-2HP',
                'brand' => 'hisense',
                'category' => 'split-air-conditioners',
                'description' => 'Hisense split air conditioner designed for powerful cooling in larger rooms.',
                'price' => 31999,
                'sale_price' => 29999,
                'quantity' => 6,
                'featured' => false,
            ],
            [
                'name' => 'Beko Electric Oven',
                'slug' => 'beko-electric-oven',
                'sku' => 'BEKO-OVEN-ELEC',
                'brand' => 'beko',
                'category' => 'electric-ovens',
                'description' => 'Beko electric oven designed for everyday home cooking and baking.',
                'price' => 17999,
                'sale_price' => 16999,
                'quantity' => 8,
                'featured' => false,
            ],
            [
                'name' => 'Sony WF-1000XM5',
                'slug' => 'sony-wf-1000xm5',
                'sku' => 'SONY-WF1000XM5',
                'brand' => 'sony',
                'category' => 'wireless-earbuds',
                'description' => 'Sony WF-1000XM5 premium wireless earbuds with advanced noise cancellation.',
                'price' => 16999,
                'sale_price' => 15999,
                'quantity' => 12,
                'featured' => true,
            ],
            [
                'name' => 'Apple AirPods Pro 2',
                'slug' => 'apple-airpods-pro-2',
                'sku' => 'APP-AIRPODS-P2',
                'brand' => 'apple',
                'category' => 'wireless-earbuds',
                'description' => 'AirPods Pro 2 wireless earbuds with active noise cancellation and Apple integration.',
                'price' => 11999,
                'sale_price' => 11499,
                'quantity' => 18,
                'featured' => true,
            ],
            [
                'name' => 'Samsung Galaxy Buds3 Pro',
                'slug' => 'samsung-galaxy-buds3-pro',
                'sku' => 'SAM-BUDS3-PRO',
                'brand' => 'samsung',
                'category' => 'wireless-earbuds',
                'description' => 'Samsung Galaxy Buds3 Pro with premium audio and noise cancellation.',
                'price' => 9999,
                'sale_price' => 9499,
                'quantity' => 15,
                'featured' => false,
            ],
            [
                'name' => 'JBL Live 660NC',
                'slug' => 'jbl-live-660nc',
                'sku' => 'JBL-LIVE660NC',
                'brand' => 'jbl',
                'category' => 'headphones',
                'description' => 'JBL Live 660NC wireless headphones with noise cancellation and rich sound.',
                'price' => 6999,
                'sale_price' => 6499,
                'quantity' => 20,
                'featured' => false,
            ],
            [
                'name' => 'Sony SRS-XB100',
                'slug' => 'sony-srs-xb100',
                'sku' => 'SONY-SRS-XB100',
                'brand' => 'sony',
                'category' => 'bluetooth-speakers',
                'description' => 'Sony SRS-XB100 compact portable Bluetooth speaker with clear sound.',
                'price' => 2999,
                'sale_price' => 2799,
                'quantity' => 25,
                'featured' => false,
            ],
            [
                'name' => 'JBL Flip 6',
                'slug' => 'jbl-flip-6',
                'sku' => 'JBL-FLIP6',
                'brand' => 'jbl',
                'category' => 'bluetooth-speakers',
                'description' => 'JBL Flip 6 portable Bluetooth speaker designed for powerful sound.',
                'price' => 4999,
                'sale_price' => 4599,
                'quantity' => 22,
                'featured' => true,
            ],
            [
                'name' => 'Samsung HW-Q600C Soundbar',
                'slug' => 'samsung-hw-q600c-soundbar',
                'sku' => 'SAM-Q600C',
                'brand' => 'samsung',
                'category' => 'soundbars',
                'description' => 'Samsung HW-Q600C soundbar designed to enhance TV audio.',
                'price' => 12999,
                'sale_price' => 11999,
                'quantity' => 9,
                'featured' => false,
            ],
            [
                'name' => 'Anker 735 Charger',
                'slug' => 'anker-735-charger',
                'sku' => 'ANK-735-CH',
                'brand' => 'anker',
                'category' => 'chargers',
                'description' => 'Anker 735 GaN charger designed to power multiple compatible devices efficiently.',
                'price' => 2499,
                'sale_price' => 2299,
                'quantity' => 35,
                'featured' => false,
            ],
            [
                'name' => 'Anker 737 Power Bank',
                'slug' => 'anker-737-power-bank',
                'sku' => 'ANK-737-PB',
                'brand' => 'anker',
                'category' => 'power-banks',
                'description' => 'Anker 737 power bank with high capacity and fast charging support.',
                'price' => 5999,
                'sale_price' => 5599,
                'quantity' => 20,
                'featured' => true,
            ],
            [
                'name' => 'Samsung 45W USB-C Charger',
                'slug' => 'samsung-45w-usb-c-charger',
                'sku' => 'SAM-45W-CH',
                'brand' => 'samsung',
                'category' => 'chargers',
                'description' => 'Samsung 45W USB-C charger designed for compatible Galaxy devices.',
                'price' => 1799,
                'sale_price' => 1649,
                'quantity' => 40,
                'featured' => false,
            ],
            [
                'name' => 'Apple MagSafe Charger',
                'slug' => 'apple-magsafe-charger',
                'sku' => 'APP-MAGSAFE-CH',
                'brand' => 'apple',
                'category' => 'wireless-chargers',
                'description' => 'Apple MagSafe Charger designed for convenient wireless charging.',
                'price' => 1999,
                'sale_price' => 1849,
                'quantity' => 30,
                'featured' => false,
            ],
            [
                'name' => 'TP-Link Archer AX55',
                'slug' => 'tp-link-archer-ax55',
                'sku' => 'TPL-AX55',
                'brand' => 'tp-link',
                'category' => 'routers',
                'description' => 'TP-Link Archer AX55 WiFi 6 router designed for fast home networking.',
                'price' => 4999,
                'sale_price' => 4599,
                'quantity' => 15,
                'featured' => true,
            ],
            [
                'name' => 'TP-Link Deco X20',
                'slug' => 'tp-link-deco-x20',
                'sku' => 'TPL-DECO-X20',
                'brand' => 'tp-link',
                'category' => 'mesh-wifi-systems',
                'description' => 'TP-Link Deco X20 mesh WiFi system designed for reliable whole-home coverage.',
                'price' => 8999,
                'sale_price' => 8499,
                'quantity' => 10,
                'featured' => false,
            ],
            [
                'name' => 'Logitech MX Keys S',
                'slug' => 'logitech-mx-keys-s',
                'sku' => 'LOG-MXKEYS-S',
                'brand' => 'logitech',
                'category' => 'keyboards',
                'description' => 'Logitech MX Keys S wireless keyboard designed for professional productivity.',
                'price' => 5999,
                'sale_price' => 5499,
                'quantity' => 18,
                'featured' => true,
            ],
            [
                'name' => 'Logitech G Pro X Superlight 2',
                'slug' => 'logitech-g-pro-x-superlight-2',
                'sku' => 'LOG-GPXSL2',
                'brand' => 'logitech',
                'category' => 'gaming-mice',
                'description' => 'Logitech G Pro X Superlight 2 lightweight wireless gaming mouse.',
                'price' => 6999,
                'sale_price' => 6499,
                'quantity' => 14,
                'featured' => true,
            ],
            [
                'name' => 'Razer BlackWidow V4',
                'slug' => 'razer-blackwidow-v4',
                'sku' => 'RAZ-BWV4',
                'brand' => 'razer',
                'category' => 'gaming-keyboards',
                'description' => 'Razer BlackWidow V4 mechanical gaming keyboard built for responsive gaming.',
                'price' => 6999,
                'sale_price' => 6499,
                'quantity' => 12,
                'featured' => false,
            ],
            [
                'name' => 'Logitech C920s Pro',
                'slug' => 'logitech-c920s-pro',
                'sku' => 'LOG-C920S',
                'brand' => 'logitech',
                'category' => 'webcams',
                'description' => 'Logitech C920s Pro webcam for video calls, streaming and remote work.',
                'price' => 3499,
                'sale_price' => 3199,
                'quantity' => 20,
                'featured' => false,
            ],
            [
                'name' => 'PlayStation 5 Pro',
                'slug' => 'playstation-5-pro',
                'sku' => 'PS5-PRO',
                'brand' => 'playstation',
                'category' => 'playstation',
                'description' => 'PlayStation 5 Pro gaming console designed for enhanced graphics and high-performance gaming.',
                'price' => 44999,
                'sale_price' => 42999,
                'quantity' => 5,
                'featured' => true,
            ],
            [
                'name' => 'Xbox Series S',
                'slug' => 'xbox-series-s',
                'sku' => 'XBX-SERIES-S',
                'brand' => 'xbox',
                'category' => 'xbox',
                'description' => 'Xbox Series S compact next-generation digital gaming console.',
                'price' => 19999,
                'sale_price' => 18999,
                'quantity' => 10,
                'featured' => false,
            ],
            [
                'name' => 'Nintendo Switch OLED',
                'slug' => 'nintendo-switch-oled',
                'sku' => 'NIN-SW-OLED',
                'brand' => 'nintendo',
                'category' => 'nintendo',
                'description' => 'Nintendo Switch OLED with a vibrant OLED screen and flexible gaming.',
                'price' => 19999,
                'sale_price' => 18999,
                'quantity' => 9,
                'featured' => true,
            ],
            [
                'name' => 'Sony DualSense Wireless Controller',
                'slug' => 'sony-dualsense-wireless-controller',
                'sku' => 'SONY-DS5',
                'brand' => 'sony',
                'category' => 'gaming-controllers',
                'description' => 'Sony DualSense wireless controller designed for PlayStation 5 gaming.',
                'price' => 3999,
                'sale_price' => 3699,
                'quantity' => 20,
                'featured' => false,
            ],
            [
                'name' => 'Xbox Wireless Controller',
                'slug' => 'xbox-wireless-controller',
                'sku' => 'XBX-CONTROLLER',
                'brand' => 'xbox',
                'category' => 'gaming-controllers',
                'description' => 'Xbox Wireless Controller with ergonomic design and responsive controls.',
                'price' => 2999,
                'sale_price' => 2799,
                'quantity' => 25,
                'featured' => false,
            ],
            [
                'name' => 'Razer BlackShark V2 Pro',
                'slug' => 'razer-blackshark-v2-pro',
                'sku' => 'RAZ-BSV2P',
                'brand' => 'razer',
                'category' => 'gaming-headsets',
                'description' => 'Razer BlackShark V2 Pro wireless gaming headset designed for competitive gaming.',
                'price' => 8999,
                'sale_price' => 8499,
                'quantity' => 10,
                'featured' => true,
            ],
            [
                'name' => 'SteelSeries Arctis Nova 7',
                'slug' => 'steelseries-arctis-nova-7',
                'sku' => 'SS-NOVA7',
                'brand' => 'steelseries',
                'category' => 'gaming-headsets',
                'description' => 'SteelSeries Arctis Nova 7 wireless gaming headset with multi-platform support.',
                'price' => 8999,
                'sale_price' => 8499,
                'quantity' => 9,
                'featured' => false,
            ],
            [
                'name' => 'Apple Watch Series 10',
                'slug' => 'apple-watch-series-10',
                'sku' => 'APP-WATCH10',
                'brand' => 'apple',
                'category' => 'smart-watches',
                'description' => 'Apple Watch Series 10 with health, fitness and smart connectivity features.',
                'price' => 24999,
                'sale_price' => 23499,
                'quantity' => 10,
                'featured' => true,
            ],
            [
                'name' => 'Samsung Galaxy Watch7',
                'slug' => 'samsung-galaxy-watch7',
                'sku' => 'SAM-WATCH7',
                'brand' => 'samsung',
                'category' => 'smart-watches',
                'description' => 'Samsung Galaxy Watch7 with fitness tracking and smart features.',
                'price' => 14999,
                'sale_price' => 13999,
                'quantity' => 14,
                'featured' => false,
            ],
            [
                'name' => 'Apple AirTag 4 Pack',
                'slug' => 'apple-airtag-4-pack',
                'sku' => 'APP-AIRTAG-4',
                'brand' => 'apple',
                'category' => 'smart-home-devices',
                'description' => 'Apple AirTag four-pack for helping locate personal items.',
                'price' => 4999,
                'sale_price' => 4699,
                'quantity' => 20,
                'featured' => false,
            ],
            [
                'name' => 'TP-Link Tapo C210',
                'slug' => 'tp-link-tapo-c210',
                'sku' => 'TPL-TAPO-C210',
                'brand' => 'tp-link',
                'category' => 'smart-cameras',
                'description' => 'TP-Link Tapo C210 indoor security camera with smart monitoring features.',
                'price' => 1999,
                'sale_price' => 1849,
                'quantity' => 25,
                'featured' => false,
            ],
            [
                'name' => 'SanDisk Ultra 256GB microSDXC',
                'slug' => 'sandisk-ultra-256gb-microsdxc',
                'sku' => 'SAND-ULTRA-256',
                'brand' => 'sandisk',
                'category' => 'memory-cards',
                'description' => 'SanDisk Ultra 256GB microSDXC memory card for compatible devices.',
                'price' => 1499,
                'sale_price' => 1349,
                'quantity' => 35,
                'featured' => false,
            ],
            [
                'name' => 'Samsung BAR Plus 128GB USB',
                'slug' => 'samsung-bar-plus-128gb-usb',
                'sku' => 'SAM-BARPLUS-128',
                'brand' => 'samsung',
                'category' => 'usb-flash-drives',
                'description' => 'Samsung BAR Plus 128GB USB flash drive for portable storage.',
                'price' => 999,
                'sale_price' => 899,
                'quantity' => 40,
                'featured' => false,
            ],
            [
                'name' => 'Kingston DataTraveler Exodia 128GB',
                'slug' => 'kingston-datatraveler-exodia-128gb',
                'sku' => 'KIN-EXODIA-128',
                'brand' => 'kingston',
                'category' => 'usb-flash-drives',
                'description' => 'Kingston DataTraveler Exodia 128GB USB flash drive for portable storage.',
                'price' => 799,
                'sale_price' => 699,
                'quantity' => 45,
                'featured' => false,
            ],
            [
                'name' => 'Samsung T7 Shield 2TB',
                'slug' => 'samsung-t7-shield-2tb',
                'sku' => 'SAM-T7SHIELD-2TB',
                'brand' => 'samsung',
                'category' => 'external-ssds',
                'description' => 'Samsung T7 Shield 2TB portable SSD designed for fast external storage.',
                'price' => 9999,
                'sale_price' => 9299,
                'quantity' => 12,
                'featured' => true,
            ],
            [
                'name' => 'Logitech Pebble 2 M350s',
                'slug' => 'logitech-pebble-2-m350s',
                'sku' => 'LOG-PEBBLE2',
                'brand' => 'logitech',
                'category' => 'mice',
                'description' => 'Logitech Pebble 2 M350s compact wireless mouse designed for quiet everyday computing.',
                'price' => 1299,
                'sale_price' => 1149,
                'quantity' => 30,
                'featured' => false,
            ],
            [
                'name' => 'Logitech K380s Keyboard',
                'slug' => 'logitech-k380s-keyboard',
                'sku' => 'LOG-K380S',
                'brand' => 'logitech',
                'category' => 'keyboards',
                'description' => 'Logitech K380s compact wireless keyboard designed for multi-device productivity.',
                'price' => 1899,
                'sale_price' => 1699,
                'quantity' => 25,
                'featured' => false,
            ],
            [
                'name' => 'UGREEN 100W USB-C Cable',
                'slug' => 'ugreen-100w-usb-c-cable',
                'sku' => 'UGR-100W-CABLE',
                'brand' => 'ugreen',
                'category' => 'charging-cables',
                'description' => 'UGREEN 100W USB-C cable designed for fast charging.',
                'price' => 699,
                'sale_price' => 599,
                'quantity' => 50,
                'featured' => false,
            ],
            [
                'name' => 'Baseus 65W GaN Charger',
                'slug' => 'baseus-65w-gan-charger',
                'sku' => 'BAS-65W-GAN',
                'brand' => 'baseus',
                'category' => 'chargers',
                'description' => 'Baseus 65W GaN charger designed for fast charging phones, tablets and compatible laptops.',
                'price' => 1699,
                'sale_price' => 1499,
                'quantity' => 35,
                'featured' => false,
            ],
            [
                'name' => 'Sony Bravia 7 55',
                'slug' => 'sony-bravia-7-55',
                'sku' => 'SONY-BRAVIA7-55',
                'brand' => 'sony',
                'category' => '4k-tvs',
                'description' => 'Sony Bravia 7 55-inch 4K Smart TV with premium picture quality and smart entertainment features.',
                'price' => 49999,
                'sale_price' => 47499,
                'quantity' => 6,
                'featured' => true,
            ],
            [
                'name' => 'TCL 65 Inch C755 QD-Mini LED',
                'slug' => 'tcl-65-inch-c755-qd-mini-led',
                'sku' => 'TCL-C755-65',
                'brand' => 'tcl',
                'category' => 'qled-tvs',
                'description' => 'TCL 65-inch QD-Mini LED Smart TV designed for vivid high-contrast entertainment.',
                'price' => 44999,
                'sale_price' => 42499,
                'quantity' => 5,
                'featured' => true,
            ],
            [
                'name' => 'Hisense 55 Inch U7K Mini LED',
                'slug' => 'hisense-55-inch-u7k-mini-led',
                'sku' => 'HIS-U7K-55',
                'brand' => 'hisense',
                'category' => '4k-tvs',
                'description' => 'Hisense 55-inch Mini LED Smart TV designed for high-contrast 4K entertainment.',
                'price' => 32999,
                'sale_price' => 30999,
                'quantity' => 7,
                'featured' => false,
            ],
            [
                'name' => 'Philips 55 Inch The One',
                'slug' => 'philips-55-inch-the-one',
                'sku' => 'PHI-THEONE-55',
                'brand' => 'philips',
                'category' => '4k-tvs',
                'description' => 'Philips 55-inch 4K Smart TV designed for everyday streaming and home entertainment.',
                'price' => 29999,
                'sale_price' => 28499,
                'quantity' => 8,
                'featured' => false,
            ],
            [
                'name' => 'Samsung 9KG Front Load Washer',
                'slug' => 'samsung-9kg-front-load-washer',
                'sku' => 'SAM-WM-9KG',
                'brand' => 'samsung',
                'category' => 'washing-machines',
                'description' => 'Samsung 9KG front-load washing machine designed for efficient everyday laundry.',
                'price' => 29999,
                'sale_price' => 27999,
                'quantity' => 7,
                'featured' => false,
            ],
            [
                'name' => 'LG 12KG Front Load Washer',
                'slug' => 'lg-12kg-front-load-washer',
                'sku' => 'LG-WM-12KG',
                'brand' => 'lg',
                'category' => 'washing-machines',
                'description' => 'LG 12KG front-load washing machine designed for larger household laundry loads.',
                'price' => 39999,
                'sale_price' => 37999,
                'quantity' => 5,
                'featured' => true,
            ],
            [
                'name' => 'Samsung 23L Microwave',
                'slug' => 'samsung-23l-microwave',
                'sku' => 'SAM-MW-23L',
                'brand' => 'samsung',
                'category' => 'microwaves',
                'description' => 'Samsung 23L microwave oven designed for convenient everyday cooking and reheating.',
                'price' => 6999,
                'sale_price' => 6499,
                'quantity' => 12,
                'featured' => false,
            ],
            [
                'name' => 'Philips 3000 Series Airfryer',
                'slug' => 'philips-3000-series-airfryer',
                'sku' => 'PHI-AF-3000',
                'brand' => 'philips',
                'category' => 'home-appliances',
                'description' => 'Philips 3000 Series Airfryer designed for convenient everyday cooking with hot-air technology.',
                'price' => 5999,
                'sale_price' => 5499,
                'quantity' => 20,
                'featured' => false,
            ],
            [
                'name' => 'Beko 14 Place Dishwasher',
                'slug' => 'beko-14-place-dishwasher',
                'sku' => 'BEKO-DW14',
                'brand' => 'beko',
                'category' => 'dishwashers',
                'description' => 'Beko 14-place dishwasher designed for efficient cleaning and convenient family use.',
                'price' => 29999,
                'sale_price' => 27999,
                'quantity' => 6,
                'featured' => false,
            ],
            [
                'name' => 'Samsung WindFree Inverter AC 1.5HP',
                'slug' => 'samsung-windfree-inverter-ac-1-5hp',
                'sku' => 'SAM-AC-WF15',
                'brand' => 'samsung',
                'category' => 'inverter-air-conditioners',
                'description' => 'Samsung WindFree inverter air conditioner designed for efficient cooling and comfortable indoor use.',
                'price' => 36999,
                'sale_price' => 34999,
                'quantity' => 5,
                'featured' => true,
            ],
            [
                'name' => 'LG Dual Inverter AC 1.5HP',
                'slug' => 'lg-dual-inverter-ac-1-5hp',
                'sku' => 'LG-AC-DUAL15',
                'brand' => 'lg',
                'category' => 'inverter-air-conditioners',
                'description' => 'LG Dual Inverter air conditioner designed for efficient cooling and energy-conscious operation.',
                'price' => 35999,
                'sale_price' => 33999,
                'quantity' => 5,
                'featured' => true,
            ],
            [
                'name' => 'Anker Soundcore Motion 300',
                'slug' => 'anker-soundcore-motion-300',
                'sku' => 'ANK-MOTION300',
                'brand' => 'anker',
                'category' => 'bluetooth-speakers',
                'description' => 'Anker Soundcore Motion 300 portable Bluetooth speaker designed for powerful portable audio.',
                'price' => 4999,
                'sale_price' => 4599,
                'quantity' => 18,
                'featured' => false,
            ],
            [
                'name' => 'JBL PartyBox Encore',
                'slug' => 'jbl-partybox-encore',
                'sku' => 'JBL-PARTYBOX-ENCORE',
                'brand' => 'jbl',
                'category' => 'bluetooth-speakers',
                'description' => 'JBL PartyBox Encore portable party speaker designed for powerful entertainment audio.',
                'price' => 15999,
                'sale_price' => 14999,
                'quantity' => 7,
                'featured' => true,
            ],
            [
                'name' => 'Sony WH-CH720N',
                'slug' => 'sony-wh-ch720n',
                'sku' => 'SONY-WHCH720N',
                'brand' => 'sony',
                'category' => 'headphones',
                'description' => 'Sony WH-CH720N wireless headphones with noise cancellation for everyday listening.',
                'price' => 6999,
                'sale_price' => 6499,
                'quantity' => 15,
                'featured' => false,
            ],
        ];
    }

    public function withRelations(): static
    {
        return $this->state(function (array $attributes) {
            $selected = collect(self::products())
                ->firstWhere('slug', $attributes['slug']);

            if (! $selected) {
                return [];
            }

            return [
                'category_id' => Category::firstOrCreate(
                    ['slug' => $selected['category']],
                    [
                        'name' => str($selected['category'])
                            ->replace('-', ' ')
                            ->title()
                            ->toString(),
                        'status' => true,
                        'sort_order' => 0,
                    ]
                )->id,

                'brand_id' => Brand::firstOrCreate(
                    ['slug' => $selected['brand']],
                    [
                        'name' => str($selected['brand'])
                            ->replace('-', ' ')
                            ->title()
                            ->toString(),
                        'status' => true,
                        'sort_order' => 0,
                    ]
                )->id,

                'slug' => $attributes['slug'].'-'.fake()->unique()->numberBetween(1, 999999),

                'sku' => $attributes['sku'].'-'.fake()->unique()->numberBetween(1, 999999),
            ];
        });
    }

    public function onSale(): static
    {
        return $this->state(function (array $attributes) {
            $price = $attributes['price'];

            return [
                'sale_price' => round($price * 0.9, 2),
            ];
        });
    }

    public function featured(): static
    {
        return $this->state([
            'featured' => true,
        ]);
    }

    public function outOfStock(): static
    {
        return $this->state([
            'quantity' => 0,
        ]);
    }

    public function inactive(): static
    {
        return $this->state([
            'status' => false,
        ]);
    }
}
